### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LiStopaD45** [muhammad-sayed-mahdy/handwritten-writer-identification#1]
Thanks for your work. I wanted to try your work, but I get an error. 
```
D:\WriterCSharper\handwritten-writer-identification-main>python src/main.py
Traceback (most recent call last):
  File "D:\WriterCSharper\handwritten-writer-identification-main\src\main.py", line 25, in <module>
    res,time = pipeline.pipe(feature='cslbcop', clf='svm',_verbose=VERBOSE, _mode=MODE, test_folder=test_folder)
  File "D:\WriterCSharper\handwritten-writer-identification-main\src\pipeline.py", line 139, in pipe
    X_tune,y_tune = step_1(train_images,_verbose, feat=feature)
  File "D:\WriterCSharper\handwritten-writer-identification-main\src\pipeline.py", line 56, in step_1
    list_images = preprocessing.preprocess(image)
  File "D:\WriterCSharper\handwritten-writer-identification-main\src\preprocessing.py", line 14, in preprocess
    xy_coord_lines = get_lines_coord(thresh)
  File "D:\WriterCSharper\handwritten-writer-identification-main\src\preprocessing.py", line 37, in get_lines_coord
    y_start = lines_indexes[ np.argmax(lines_indexes > (lines_indexes[0]+150) ) ]
IndexError: index 0 is out of bounds for axis 0 with size 0
```
How can I fix this?

**Comment by muhammad-sayed-mahdy** [comment]
can you share what's in your `data` folder ?

**Comment by LiStopaD45** [comment]
![image](https://github.com/muhammad-sayed-mahdy/handwritten-writer-identification/assets/31504189/293148ac-879c-4eaa-a474-a2fdb51c5738)

![image](https://github.com/muhammad-sayed-mahdy/handwritten-writer-identification/assets/31504189/7a717a86-6013-4e0c-b369-e85e16c35a1d)

![image](https://github.com/muhammad-sayed-mahdy/handwritten-writer-identification/assets/31504189/9a54de85-4ed0-44d7-b884-1683355f6a4c)

**Comment by muhammad-sayed-mahdy** [comment]
I'm unable to reproduce the error, can you share the data folder as ZIP file

**Comment by LiStopaD45** [comment]
I am grateful to you for your prompt participation in solving my problem. 
I made an archive of the data folder.
 I'm using Windows 10 x64. 
I'm starting the journey of working with python on windows, maybe I'm missing something.

[data.zip](https://github.com/muhammad-sayed-mahdy/handwritten-writer-identification/files/14895063/data.zip)

**Comment by fraciccio2** [comment]
I also encountered the same error, by any chance were you able to resolve it?
